version: '3'
volumes:
  pgdata:
services:
  python: &python
    # image: python:3.5
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    volumes:
      - .:/django_postgres_docker_celery_rabbitmq
    ports:
      - 8000:8000
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - rabbitmq
      - celery_worker
  ## message queue for celery
  rabbitmq:
    image: rabbitmq:3.8-alpine
  celery_worker:
    <<: *python
   # command: celery -A django_docker_celery_rabbitmq worker --loglevel=info
   # command: bash -c "celery -A django_docker_celery_rabbitmq worker -l info && celery -A django_docker_celery_rabbitmq beat -l info"
    command: celery -A django_postgres_docker_celery_rabbitmq worker -l info -B
    ports: []
    depends_on:
      - rabbitmq
